### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by kodeine** [maciejtreder/angular-external-module#1]
Hello,
I have an app which needs universal support. i came across your post on stackoverflow that you've implemented this. can you please guide how this can be used for AWS Lambda deployment?

Thanks

**Comment by maciejtreder** [comment]
@kodeine Checkout this repo: https://github.com/maciejtreder/angular-universal-pwa

This is boilerplate for Angular Universal deployed on AWS Lambda. You can also follow me on twitter, I am preparing series of articles about Angular, latest news about them can be found there.
